import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>NFT</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 className={"bg-red-400"}>Welcome to NFT</h1>
    </div>
  );
}
